export const LIST_LANGUAGES = 'LIST_LANGUAGES';
export const PICK_LANGUAGE = 'PICK_LANGUAGE';

export const FREQUENCYLIST_REQUEST = 'FREQUENCYLIST_REQUEST';
export const FREQUENCYLIST_SUCCESS = 'FREQUENCYLIST_SUCCESS';
export const FREQUENCYLIST_ERROR = 'FREQUENCYLIST_ERROR';

export const NGRAM_REQUEST = 'NGRAM_REQUEST';
export const NGRAM_SUCCESS = 'NGRAM_SUCCESS';
export const NGRAM_ERROR = 'NGRAM_ERROR';

export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SORT_TABLE = 'SORT_TABLE';
